---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "AYO API Documentation"
host: "172.24.252.167:10010"
basePath: "/ayo"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /homepage:
    post:
      tags:
      - "homepage"
      summary: "get homepage based on specified geo"
      description: ""
      operationId: "homepage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "homepage geo that might contain lat-lon, geoId, landmarkId.\
          \ if null given, default will be Jakarta"
        required: true
        schema:
          $ref: "#/definitions/HomepageRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HomepageResponse"
        400:
          description: "Invalid geo"
      x-swagger-router-controller: "Homepage"
  /poi:
    post:
      tags:
      - "poi"
      summary: "get poi detail based on poi id"
      description: ""
      operationId: "poi"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/POIRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/POIResponse"
        400:
          description: "Invalide POI id"
      x-swagger-router-controller: "Poi"
  /location:
    post:
      tags:
      - "location"
      summary: "get the location"
      description: ""
      operationId: "location"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/LocationRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationResponse"
        400:
          description: "Invalide  query"
      x-swagger-router-controller: "Location"
  /search/spec:
    post:
      tags:
      - "searchresultspec"
      summary: "get search result page spec"
      description: "Api Call to get Search Result Spec; like filter and sort"
      operationId: "search_spec"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/SearchResultSpecRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResultSpecResponse"
        400:
          description: "Invalide  query"
      x-swagger-router-controller: "SearchResult"
  /search/list:
    post:
      tags:
      - "searchresultlist"
      summary: "get search result"
      description: "Api Call to get Search Result"
      operationId: "search_list"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/SearchResultRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResultResponse"
        400:
          description: "Invalide  query"
      x-swagger-router-controller: "SearchResult"
  /search/further:
    post:
      tags:
      - "searchresultfurtheraway"
      summary: "get search result further away result"
      description: "Api Call to get Search Result for Further Away Result"
      operationId: "search_further"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/SearchResultRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResultResponse"
        400:
          description: "Invalide  query"
      x-swagger-router-controller: "SearchResult"
definitions:
  GeoDisplay:
    type: "object"
    required:
    - "id"
    - "locationType"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Jakarta"
      locationType:
        type: "string"
        example: "GEO"
        description: "Type of location"
        enum:
        - "GEO"
        - "LANDMARK"
    example:
      name: "Jakarta"
      locationType: "GEO"
      id: 0
  RestaurantTile:
    type: "object"
    required:
    - "id"
    - "imageUrl"
    - "locationLabel"
    - "name"
    properties:
      id:
        type: "string"
        example: "123"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      name:
        type: "string"
        example: "Bureau Cafe"
      locationLabel:
        type: "string"
        example: "Central Park, Slipi"
      cuisineType:
        type: "string"
        example: "Western"
      ratingDisplay:
        $ref: "#/definitions/RatingDisplay"
    example:
      ratingDisplay:
        rating: 4.5999999999999996447286321199499070644378662109375
        ratingColor:
          r: 153
          b: 152
          g: 37
      imageUrl: "http://tny.im/jA-"
      name: "Bureau Cafe"
      locationLabel: "Central Park, Slipi"
      id: "123"
      cuisineType: "Western"
  RatingDisplay:
    type: "object"
    required:
    - "rating"
    - "ratingColor"
    properties:
      rating:
        type: "number"
        example: 4.5999999999999996447286321199499070644378662109375
      ratingColor:
        $ref: "#/definitions/Color"
    example:
      rating: 4.5999999999999996447286321199499070644378662109375
      ratingColor:
        r: 153
        b: 152
        g: 37
  Banner:
    type: "object"
    required:
    - "deeplink"
    - "imageUrl"
    properties:
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      deeplink:
        type: "string"
        example: "http://heyayo.id"
    example:
      imageUrl: "http://tny.im/jA-"
      deeplink: "http://heyayo.id"
  NearbyRestaurantDisplay:
    type: "object"
    required:
    - "imageUrl"
    - "label"
    properties:
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      label:
        type: "string"
        example: "See restaurant around me"
    example:
      imageUrl: "http://tny.im/jA-"
      label: "See restaurant around me"
  DishTile:
    type: "object"
    required:
    - "id"
    - "imageUrl"
    properties:
      id:
        type: "string"
        example: "PIZZA"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
    example:
      imageUrl: "http://tny.im/jA-"
      id: "PIZZA"
  Section:
    type: "object"
    required:
    - "dishes"
    - "groupType"
    - "restaurants"
    - "title"
    properties:
      title:
        type: "string"
        example: "Restoran di Jakarta"
      groupType:
        type: "string"
        example: "RESTAURANT"
        enum:
        - "RESTAURANT"
        - "DISH"
        - "CUISINE"
      restaurants:
        type: "array"
        items:
          $ref: "#/definitions/RestaurantTile"
      dishes:
        type: "array"
        items:
          $ref: "#/definitions/DishTile"
    example:
      groupType: "RESTAURANT"
      restaurants:
      - ratingDisplay:
          rating: 4.5999999999999996447286321199499070644378662109375
          ratingColor:
            r: 153
            b: 152
            g: 37
        imageUrl: "http://tny.im/jA-"
        name: "Bureau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
        cuisineType: "Western"
      - ratingDisplay:
          rating: 4.5999999999999996447286321199499070644378662109375
          ratingColor:
            r: 153
            b: 152
            g: 37
        imageUrl: "http://tny.im/jA-"
        name: "Bureau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
        cuisineType: "Western"
      dishes:
      - imageUrl: "http://tny.im/jA-"
        id: "PIZZA"
      - imageUrl: "http://tny.im/jA-"
        id: "PIZZA"
      title: "Restoran di Jakarta"
  HomepageDataResponse:
    type: "object"
    required:
    - "banners"
    - "geoDisplay"
    - "sections"
    properties:
      geoDisplay:
        $ref: "#/definitions/GeoDisplay"
      banners:
        type: "array"
        items:
          $ref: "#/definitions/Banner"
      nearbyRestaurantDisplay:
        $ref: "#/definitions/NearbyRestaurantDisplay"
      sections:
        type: "array"
        items:
          $ref: "#/definitions/Section"
    example:
      geoDisplay:
        name: "Jakarta"
        locationType: "GEO"
        id: 0
      banners:
      - imageUrl: "http://tny.im/jA-"
        deeplink: "http://heyayo.id"
      - imageUrl: "http://tny.im/jA-"
        deeplink: "http://heyayo.id"
      nearbyRestaurantDisplay:
        imageUrl: "http://tny.im/jA-"
        label: "See restaurant around me"
      sections:
      - groupType: "RESTAURANT"
        restaurants:
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        dishes:
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        title: "Restoran di Jakarta"
      - groupType: "RESTAURANT"
        restaurants:
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        dishes:
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        title: "Restoran di Jakarta"
  GeoLocation:
    type: "object"
    required:
    - "lat"
    - "lon"
    properties:
      lat:
        type: "number"
        example: 23.449999999999999289457264239899814128875732421875
      lon:
        type: "number"
        example: 68.4500000000000028421709430404007434844970703125
    example:
      lon: 68.4500000000000028421709430404007434844970703125
      lat: 23.449999999999999289457264239899814128875732421875
  HomepageRequest:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/HomePageRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        geoLocation:
          lon: 68.4500000000000028421709430404007434844970703125
          lat: 23.449999999999999289457264239899814128875732421875
        geoDisplay:
          name: "Jakarta"
          locationType: "GEO"
          id: 0
      context:
        session: "session"
        clientInterface: "clientInterface"
  ContextRequest:
    type: "object"
    required:
    - "clientInterface"
    properties:
      session:
        type: "string"
      clientInterface:
        type: "string"
    example:
      session: "session"
      clientInterface: "clientInterface"
  ContextResponse:
    type: "object"
    properties:
      session:
        type: "string"
    example:
      session: "session"
  HomePageRequestData:
    type: "object"
    required:
    - "geoDisplay"
    - "geoLocation"
    properties:
      geoDisplay:
        $ref: "#/definitions/GeoDisplay"
      geoLocation:
        $ref: "#/definitions/GeoLocation"
    example:
      geoLocation:
        lon: 68.4500000000000028421709430404007434844970703125
        lat: 23.449999999999999289457264239899814128875732421875
      geoDisplay:
        name: "Jakarta"
        locationType: "GEO"
        id: 0
  HomepageResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/HomepageDataResponse"
      context:
        $ref: "#/definitions/ContextResponse"
    example:
      data:
        geoDisplay:
          name: "Jakarta"
          locationType: "GEO"
          id: 0
        banners:
        - imageUrl: "http://tny.im/jA-"
          deeplink: "http://heyayo.id"
        - imageUrl: "http://tny.im/jA-"
          deeplink: "http://heyayo.id"
        nearbyRestaurantDisplay:
          imageUrl: "http://tny.im/jA-"
          label: "See restaurant around me"
        sections:
        - groupType: "RESTAURANT"
          restaurants:
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          dishes:
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          title: "Restoran di Jakarta"
        - groupType: "DISH"
          restaurants:
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          dishes:
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          title: "Restoran di Jakarta"
      context:
        session: "session"
  HourMinute:
    type: "object"
    required:
    - "hour"
    properties:
      hour:
        type: "integer"
        example: 7
        minimum: 0
        maximum: 23
      minutes:
        type: "integer"
        example: 0
        minimum: 0
        maximum: 59
    example:
      hour: 7
      minutes: 0
  OpenHour:
    type: "object"
    required:
    - "closed"
    - "isToday"
    - "operationHours"
    - "weekDay"
    properties:
      weekDay:
        type: "string"
        example: "SUNDAY"
        enum:
        - "SUNDAY"
        - "MONDAY"
        - "TUESDAY"
        - "WEDNESDAY"
        - "THURSDAY"
        - "FRIDAY"
        - "SATURDAY"
      operationHours:
        type: "array"
        items:
          $ref: "#/definitions/OperationHour"
      closed:
        type: "boolean"
        example: false
      isToday:
        type: "boolean"
        example: false
    example:
      weekDay: "SUNDAY"
      operationHours:
      - closeTime:
          hour: 7
          minutes: 0
        openTime:
          hour: 7
          minutes: 0
      - closeTime:
          hour: 7
          minutes: 0
        openTime:
          hour: 7
          minutes: 0
      isToday: false
      closed: false
  OperationHour:
    type: "object"
    required:
    - "closeTime"
    - "openTime"
    properties:
      openTime:
        $ref: "#/definitions/HourMinute"
      closeTime:
        $ref: "#/definitions/HourMinute"
    example:
      closeTime:
        hour: 7
        minutes: 0
      openTime:
        hour: 7
        minutes: 0
  Tag:
    type: "object"
    required:
    - "imageUrl"
    - "label"
    properties:
      label:
        type: "string"
        example: "Historical Building"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
    example:
      imageUrl: "http://tny.im/jA-"
      label: "Historical Building"
  BestKnownFor:
    type: "object"
    required:
    - "description"
    properties:
      description:
        type: "string"
        example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
          \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
          \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus gravida\
          \ cursus. Maecenas congue dictum consectetur. Fusce in nibh ut mi consectetur\
          \ pretium. "
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
    example:
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
        \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
        \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus gravida\
        \ cursus. Maecenas congue dictum consectetur. Fusce in nibh ut mi consectetur\
        \ pretium. "
      tags:
      - imageUrl: "http://tny.im/jA-"
        label: "Historical Building"
      - imageUrl: "http://tny.im/jA-"
        label: "Historical Building"
  LocationInfo:
    type: "object"
    required:
    - "address"
    - "geoLocation"
    - "label"
    properties:
      label:
        type: "string"
        example: "PIK Avenue, 2nd Floor"
      address:
        type: "string"
        example: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
      geoLocation:
        $ref: "#/definitions/GeoLocation"
    example:
      address: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
      geoLocation:
        lon: 68.4500000000000028421709430404007434844970703125
        lat: 23.449999999999999289457264239899814128875732421875
      label: "PIK Avenue, 2nd Floor"
  FeatureFacility:
    type: "object"
    required:
    - "available"
    - "iconImageUrl"
    - "label"
    properties:
      iconImageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      label:
        type: "string"
        example: "Air Conditioned"
      available:
        type: "boolean"
        example: true
    example:
      iconImageUrl: "http://tny.im/jA-"
      available: true
      label: "Air Conditioned"
  RestaurantNearby:
    type: "object"
    required:
    - "id"
    - "imageUrl"
    - "locationLabel"
    - "name"
    - "restaurantType"
    properties:
      id:
        type: "string"
        example: "123"
      name:
        type: "string"
        example: "Bereau Cafe"
      locationLabel:
        type: "string"
        example: "Central Park, Slipi"
      restaurantType:
        type: "string"
        example: "Western"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
    example:
      restaurantType: "Western"
      imageUrl: "http://tny.im/jA-"
      name: "Bereau Cafe"
      locationLabel: "Central Park, Slipi"
      id: "123"
  Photo:
    type: "object"
    required:
    - "category"
    - "imageUrl"
    - "mainSubcategory"
    - "subcategories"
    properties:
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      category:
        type: "string"
        example: "AMBIENCE"
      mainSubcategory:
        type: "string"
        example: "Indoor seating"
      subcategories:
        type: "array"
        items:
          type: "string"
    example:
      imageUrl: "http://tny.im/jA-"
      category: "AMBIENCE"
      mainSubcategory: "Indoor Seating"
      subcategories:
      - "subcategories"
      - "subcategories"
  PhotoGroupDisplay:
    type: "object"
    required:
        - "photos"
        - "tab"
    properties:
        photos:
            type: "array"
            items:
                $ref: "#/definitions/Photo"
        tab:
            type: "string"
            example: "Menu"
    example:
        tab: "Menu"
        photos:
        - imageUrl: "http://tny.im/jA-"
          category: "AMBIENCE"
          mainSubcategory: "Indoor seating"
          subcategories:
            - "subcategories"
            - "subcategories"
        - imageUrl: "http://tny.im/jA-"
          category: "AMBIENCE"
          mainSubcategory: "Indoor seating"
          subcategories:
            - "subcategories"
            - "subcategories"
  Color:
    type: "object"
    required:
    - "b"
    - "g"
    - "r"
    properties:
      r:
        type: "integer"
        minimum: 0
        maximum: 255
      g:
        type: "integer"
        minimum: 0
        maximum: 255
      b:
        type: "integer"
        minimum: 0
        maximum: 255
    example:
      r: 153
      b: 152
      g: 37
  POIStatus:
    type: "object"
    required:
    - "status"
    - "statusLabel"
    properties:
      status:
        type: "string"
        example: "PERMANENTLY_CLOSED"
        enum:
        - "NEW"
        - "COMING_SOON"
        - "TEMP_CLOSED"
        - "PERMANENTLY_CLOSED"
      statusLabel:
        type: "string"
        example: "Opening again at 11 dec 2019"
    example:
      statusLabel: "Opening again at 11 dec 2019"
      status: "PERMANENTLY_CLOSED"
  Price:
    type: "object"
    required:
    - "priceLabel"
    properties:
      priceLabel:
        type: "string"
        example: "Around Rp 100.000 per person"
      priceDetail:
        type: "string"
        example: "price for 1 dish + 1 beverages"
    example:
      priceDetail: "price for 1 dish + 1 beverages"
      priceLabel: "Around Rp 100.000 per person"
  POIResponseData:
    type: "object"
    required:
    - "cuisineDishTypes"
    - "featureFacilities"
    - "id"
    - "poiPhotosList"
    - "locationInfo"
    - "mainCuisine"
    - "mainDish"
    - "mainRestaurantType"
    - "name"
    - "openHourToday"
    - "openHours"
    - "phoneNumbers"
    - "photo"
    - "menu"
    - "price"
    - "restaurantTypes"
    properties:
      id:
        type: "string"
        example: "123"
      name:
        type: "string"
        example: "Chir Chir fusion Chicken"
      bestKnownFor:
        $ref: "#/definitions/BestKnownFor"
      locationInfo:
        $ref: "#/definitions/LocationInfo"
      mainRestaurantType:
        type: "string"
        example: "Casual Dining"
      mainCuisine:
        type: "string"
        example: "Korean"
      mainDish:
        type: "string"
        example: "Fried Chicken"
      POIstatus:
        $ref: "#/definitions/POIStatus"
      price:
        $ref: "#/definitions/Price"
      openHourToday:
        $ref: "#/definitions/OpenHour"
      openHours:
        type: "array"
        items:
          $ref: "#/definitions/OpenHour"
      restaurantTypes:
        type: "array"
        items:
          type: "string"
      cuisineDishTypes:
        type: "array"
        items:
          type: "string"
      highlightedFeatureFacilities:
        type: "array"
        items:
          $ref: "#/definitions/FeatureFacility"
      featureFacilities:
        type: "array"
        items:
          $ref: "#/definitions/FeatureFacility"
      phoneNumbers:
        type: "array"
        items:
          type: "string"
      paymentMethods:
        type: "array"
        items:
          $ref: "#/definitions/FeatureFacility"
      restaurantNearbies:
        type: "array"
        items:
          $ref: "#/definitions/RestaurantNearby"
      photo:
        $ref: "#/definitions/PhotoGroupDisplay"
      menu:
        $ref: "#/definitions/PhotoGroupDisplay"
      poiPhotosList:
        type: "array"
        items:
          type: "string"
    example:
      openHours:
      - weekDay: "SUNDAY"
        operationHours:
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        isToday: false
        closed: false
      - weekDay: "SUNDAY"
        operationHours:
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        isToday: false
        closed: false
      bestKnownFor:
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
          \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
          \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus gravida\
          \ cursus. Maecenas congue dictum consectetur. Fusce in nibh ut mi consectetur\
          \ pretium. "
        tags:
        - imageUrl: "http://tny.im/jA-"
          label: "Historical Building"
        - imageUrl: "http://tny.im/jA-"
          label: "Historical Building"
      locationInfo:
        address: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
        geoLocation:
          lon: 68.4500000000000028421709430404007434844970703125
          lat: 23.449999999999999289457264239899814128875732421875
        label: "PIK Avenue, 2nd Floor"
      restaurantNearbies:
      - restaurantType: "Western"
        imageUrl: "http://tny.im/jA-"
        name: "Bereau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
      - restaurantType: "Western"
        imageUrl: "http://tny.im/jA-"
        name: "Bereau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
      mainCuisine: "Korean"
      POIstatus:
        statusLabel: "Opening again at 11 dec 2019"
        status: "PERMANENTLY_CLOSED"
      mainDish: "Fried Chicken"
      mainRestaurantType: "Casual Dining"

      phoneNumbers:
      - "phoneNumbers"
      - "phoneNumbers"
      restaurantTypes:
      - "restaurantTypes"
      - "restaurantTypes"
      poiPhotosList:
      - "imageUrlList"
      - "imageUrlList"
      featureFacilities:
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      price:
        priceDetail: "price for 1 dish + 1 beverages"
        priceLabel: "Around Rp 100.000 per person"
      paymentMethods:
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      name: "Chir Chir fusion Chicken"
      id: "123"
      openHourToday:
        weekDay: "SUNDAY"
        operationHours:
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        isToday: false
        closed: false
      highlightedFeatureFacilities:
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
  POIRequestData:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        example: "123"
    example:
      id: "123"
  POIResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/POIResponseData"
      context:
        $ref: "#/definitions/ContextResponse"
    example:
      data:
        openHours:
        - weekDay: "SUNDAY"
          operationHours:
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          isToday: false
          closed: false
        - weekDay: "SUNDAY"
          operationHours:
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          isToday: false
          closed: false
        bestKnownFor:
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
            \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
            \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus\
            \ gravida cursus. Maecenas congue dictum consectetur. Fusce in nibh ut\
            \ mi consectetur pretium. "
          tags:
          - imageUrl: "http://tny.im/jA-"
            label: "Historical Building"
          - imageUrl: "http://tny.im/jA-"
            label: "Historical Building"
        locationInfo:
          address: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
          geoLocation:
            lon: 68.4500000000000028421709430404007434844970703125
            lat: 23.449999999999999289457264239899814128875732421875
          label: "PIK Avenue, 2nd Floor"
        restaurantNearbies:
        - restaurantType: "Western"
          imageUrl: "http://tny.im/jA-"
          name: "Bereau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
        - restaurantType: "Western"
          imageUrl: "http://tny.im/jA-"
          name: "Bereau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
        mainCuisine: "Korean"
        POIstatus:
          statusLabel: "Opening again at 11 dec 2019"
          status: "PERMANENTLY_CLOSED"
        mainDish: "Fried Chicken"
        mainRestaurantType: "Casual Dining"
        photo:
          tab: "ALL"
          photos:
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
        phoneNumbers:
        - "phoneNumbers"
        - "phoneNumbers"
        restaurantTypes:
        - "restaurantTypes"
        - "restaurantTypes"
        poiPhotosList:
        - "imageUrlList"
        - "imageUrlList"
        featureFacilities:
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        price:
          priceDetail: "price for 1 dish + 1 beverages"
          priceLabel: "Around Rp 100.000 per person"
        paymentMethods:
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        name: "Chir Chir fusion Chicken"
        id: "123"
        openHourToday:
          weekDay: "SUNDAY"
          operationHours:
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          isToday: false
          closed: false
        highlightedFeatureFacilities:
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        menu:
          tab: "Menu"
          photos:
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
        cuisineDishTypes:
        - "cuisineDishTypes"
        - "cuisineDishTypes"
      context:
        session: "session"
  POIRequest:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/POIRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        id: "123"
      context:
        session: "session"
        clientInterface: "clientInterface"
  LocationRequestData:
    type: "object"
    required:
    - "query"
    properties:
      query:
        type: "string"
    example:
      query: "123"
  LocationRequest:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/LocationRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        query: "slipi"
      context:
        session: "session"
        clientInterface: "clientInterface"
  LocationResponseData:
    type: "object"
    required:
    - "locations"
    properties:
      locations:
        type: "array"
        items:
          type: "object"
          properties:
            geoDisplay:
              $ref: "#/definitions/GeoDisplay"
  LocationResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/LocationResponseData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        locations:
          - geoDisplay:
              name: "Jakarta, Indonesia"
              locationType: "GEO"
              id: 1
          - geoDisplay:
              name: "Atma Jaya, Jakarta"
              locationType: "GEO"
              id: 2
          - geoDisplay:
              name: "Wisma 77 Tower 2, Jakarta"
              locationType: "GEO"
              id: 3
          - geoDisplay:
              name: "Taman Wisata Jaya Ancol"
              locationType: "GEO"
              id: 4
          - geoDisplay:
              name: "Ragunan"
              locationType: "GEO"
              id: 5
          - geoDisplay:
              name: "Gedung Citicon, Slipi"
              locationType: "GEO"
              id: 6
          - geoDisplay:
              name: "Menara Peninsula"
              locationType: "GEO"
              id: 7
      context:
        session: "session"
        clientInterface: "clientInterface"
  SearchResultRequest:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/SearchResultRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        geoLocation:
          lon: 68.4500000000000028421709430404007434844970703125
          lat: 23.449999999999999289457264239899814128875732421875
        geoDisplay:
          name: "Jakarta"
          locationType: "GEO"
          id: 0
        filter:
          quick_filter: 
            - "Open Now"
            - "24 Hours"
          rating: 
            - "rating"
            - "rating"
          price:
            - "price"
            - "price"
          type:
            - "type"
            - "type"
          cuisine:
            - "cuisine"
            - "cuisine"
          dish:
            - "dish"
            - "dish"
          dietary:
            - "dietary"
            - "dietary"
          facility_list:
            - "facility_list"
            - "facility_list"
        sort: "Popularity"
        limit: 20
        skip: 20
      context:
        session: "session"
        clientInterface: "clientInterface"
  SearchResultRequestData:
    type: "object"
    required: 
      - "geoDisplay"
      - "geoLocation"
    properties:
      geoDisplay: 
       $ref: "#/definitions/GeoDisplay"
      geoLocation:
        $ref: "#/definitions/GeoLocation"
      filter:
       $ref: "#/definitions/SearchResultFilterBase"
      sort:
        type: "string"
        example: "Popularity"
      limit:
        type: "integer"
        format: "int64"
      skip:
        type: "integer"
        format: "int64"
    example:
      geoLocation:
        lon: 68.4500000000000028421709430404007434844970703125
        lat: 23.449999999999999289457264239899814128875732421875
      geoDisplay:
        name: "Jakarta"
        locationType: "GEO"
        id: 0
      filter:
        quick_filter: 
          - "24 Hours"
          - "Open Now"
        rating: 
          - "3+"
          - "4+"        
        price: 
          - "Fine Dining"
          - "Casual Dining"
        type: 
          - "Fine Dining"
          - "Casual Dining"
        cuisine: 
          - "Chinese"
          - "Indonesian"
        dish: 
          - "Padang"
          - "Sushi"
        dietary: 
          - "Vegan"
          - "Halal"
        facility_list: 
          - "Toilet"
          - "Praying Room"
      sort: "Popularity" 
      limit: 20
      skip: 20
  SearchResultFilterBase:
    type: "object"
    required:
    - "quick_filter"
    - "rating"
    - "price"
    - "type"
    - "cuisine"
    - "dish"
    - "dietary"
    - "facility_list"
    properties:
      quick_filter:
       type: "array"
       items:
          type: "string"
      rating:
       type: "array"
       items:
          type: "string"
      price:
       type: "array"
       items:
          type: "string"    
      type:
       type: "array"
       items:
          type: "string"
      cuisine:
       type: "array"
       items:
          type: "string"
      dish:
       type: "array"
       items:
          type: "string"
      dietary:
       type: "array"
       items:
          type: "string"
      facility_list:
       type: "array"
       items:
          type: "string"
  SearchResultSpecRequest:        
    type: "object"
    required:
    - "context"
    properties:
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      context:
        session: "session"
        clientInterface: "clientInterface"
  SearchResultSpecResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/SearchResultSpecData"
      context:
        $ref: "#/definitions/ContextResponse"
  SearchResultSpecData:
    type: "object"
    required:
    - "filter_spec"
    - "sort_spec"
    properties:
      filter_spec:
        $ref: "#/definitions/SearchResultFilterSpec"
      sort_spec:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultSortSpec"
  SearchResultSortSpec:
    type: "object"
    required:
    - "id"
    - "label"
    properties:
      id:
        type: "string"
        example: "lowest"
      label:
        type: "string"
        example: "Sort By: Lowest to Highest"
    example:
      id: "lowest"
      label: "Sort By: Lowest to Highest"
  SearchResultFilterSpec:
    type: "object"
    required:
    - "quick_filter"
    - "rating"
    - "price"
    - "type"
    - "cuisine"
    - "dish"
    - "dietary"
    - "facility_list"
    properties:
      quick_filter:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      rating:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      price:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"   
      type:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      cuisine:
        type: "array" 
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      dish:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      dietary:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      facility_list:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"  
    example:
      quick_filter:
      - id: "open"
        label: "open 24 Hours"
      rating:
      - id: "open"
        label: "open 24 Hours"
      price:
      - id: "open"
        label: "open 24 Hours"
      type:
      - id: "open"
        label: "open 24 Hours"
      cuisine:
      - id: "open"
        label: "open 24 Hours"
      dish:
      - id: "open"
        label: "open 24 Hours"
      dietary:
      - id: "open"
        label: "open 24 Hours"
      facility_list:
      - id: "open"
        label: "open 24 Hours"
      - id: "open"
        label: "open 24 Hours"
        icon: "http://tny.im/jA-"
  SearchResultFilterItem:
    type: "object"
    required:
    - "id"
    - "label"
    properties:
      id:
        type: "string"
        example: "open"
      label:
        type: "string"
        example: "Open Now"
      icon:
        type: string
        example: "http://tny.im/jA-"
    example:
      id: "open"
      label: "Open 24 Hours"
      icon: "http://tny.im/jA-"
  SearchResultResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/SearchResultDataResponse"
      context:
        $ref: "#/definitions/ContextResponse"
  SearchResultDataResponse:
    type: "object"
    required:
    - "restaurant_list"
    properties:
      restaurant_list:
        type: "array"
        items:
          $ref: "#/definitions/RestaurantCard"
  RestaurantCard:
    type: "object"
    required:
    - "name"
    - "main_type"
    - "main_cuisine"
    - "address"
    properties:
      name:
        type: "string"
      main_type:
        type: "string"
      main_cuisine:
        type: "string"
      main_dish:
        type: "string"
      image_list:
        type: "array"
        items:
          type: "string"
      status:
        type: "string"
        example: "PERMANENTLY_CLOSED"
        enum:
        - "OPEN"
        - "CLOSED"
        - "TEMPORARY_CLOSED"
        - "COMING_SOON"
        - "PERMANENTLY_CLOSED"
      open_time:
        type: "string"
        example: "09.00 - 17.00 (Thu)"
      distance:
        type: "number"
        example: 0.7
      address:
        type: "string"
        example: "Plaza Indonesia Mall, Lt 3"
      menu:
        type: array
        items:
          $ref: "#/definitions/Photo"
      label:
        type: "array"
        items: 
          type: "string"
          enum:
          - "Trending"
          - "New"
    example:
      name: "Healthy Kitchen by Julius V"
      main_type: "Casual Dining"
      main_cuisine: "Vegetarian"
      main_dish: "Capcay"
      image_list:
      - "http://tny.im/jA-"
      - "http://tny.im/jA-"
      - "http://tny.im/jA-"
      status: "OPEN"
      open_time: "09.00 - 21.00 (Thu)"
      distance: 0.7
      address: "Senopati, Jakarta Selatan"
      menu: 
        - imagerUrl: "http://tny.im/jA-"
          category: "Menu"
          mainSubcategory: "Sub Category"
          subcategories: 
          - "subcategory 1"
          - "subcategory 2"
        - imagerUrl: "http://tny.im/jA-"
          category: "Menu"
          mainSubcategory: "Sub Category"
          subcategories: 
          - "subcategory 1"
          - "subcategory 2"    
      label:
      - "Trending"
      - "New" 